import type { AdminRoleKey } from "@prisma/client";

const ADMIN_PERMISSION_KEYS = [
  "USER_VIEW",
  "USER_SUSPEND",
  "USER_REACTIVATE",
  "USER_SESSION_REVOKE",
  "WORKER_VIEW",
  "WORKER_VERIFY",
  "WORKER_REJECT_VERIFICATION",
  "POST_DELETE",
  "COMMENT_DELETE",
  "REVIEW_DELETE",
  "REPORT_VIEW",
  "REPORT_UPDATE",
  "MODERATION_CASE_ASSIGN",
  "MODERATION_CASE_ACTION",
  "SUPPORT_TICKET_VIEW",
  "SUPPORT_TICKET_ASSIGN",
  "SUPPORT_TICKET_RESPOND",
  "AUDIT_LOG_VIEW",
  "ANALYTICS_VIEW_OVERVIEW",
  "ANALYTICS_VIEW_SEARCH",
  "ANALYTICS_VIEW_ENGAGEMENT",
  "CONFIG_VIEW",
  "CONFIG_UPDATE",
  "FEATURE_FLAG_VIEW",
  "FEATURE_FLAG_UPDATE",
  "CITY_VIEW",
  "CITY_CREATE",
  "CITY_UPDATE",
  "ROLE_VIEW",
  "PERMISSION_VIEW",
  "ROLE_PERMISSION_UPDATE",
  "ADMIN_ROLE_ASSIGN",
  "ADMIN_ROLE_REMOVE",
  "FULL_ACCESS",
  "SERVICE_REQUEST_VIEW",
  "BOOKING_VIEW",
  "FEATURED_WORKER_MANAGE",
  "FRAUD_SIGNAL_VIEW",
  "FRAUD_SIGNAL_ACTION",
  "SYSTEM_HEALTH_VIEW",
  "CONTENT_VIEW",
  "NOTIFICATION_BROADCAST",
  "ANALYTICS_VIEW_MARKETPLACE"
] as const;

const DANGEROUS_ADMIN_PERMISSIONS = new Set<string>([
  "USER_SUSPEND",
  "USER_REACTIVATE",
  "USER_SESSION_REVOKE",
  "WORKER_VERIFY",
  "WORKER_REJECT_VERIFICATION",
  "POST_DELETE",
  "COMMENT_DELETE",
  "REVIEW_DELETE",
  "REPORT_UPDATE",
  "MODERATION_CASE_ACTION",
  "SUPPORT_TICKET_ASSIGN",
  "CONFIG_UPDATE",
  "FEATURE_FLAG_UPDATE",
  "CITY_CREATE",
  "CITY_UPDATE",
  "FEATURED_WORKER_MANAGE",
  "FRAUD_SIGNAL_ACTION",
  "ADMIN_ROLE_ASSIGN",
  "ADMIN_ROLE_REMOVE",
  "ROLE_PERMISSION_UPDATE",
  "NOTIFICATION_BROADCAST"
]);

const DEFAULT_ROLE_PERMISSION_KEYS: Record<AdminRoleKey, string[]> = {
  MODERATOR: [
    "USER_VIEW",
    "WORKER_VIEW",
    "POST_DELETE",
    "COMMENT_DELETE",
    "REVIEW_DELETE",
    "REPORT_VIEW",
    "REPORT_UPDATE",
    "MODERATION_CASE_ASSIGN",
    "MODERATION_CASE_ACTION",
    "ANALYTICS_VIEW_ENGAGEMENT",
    "FRAUD_SIGNAL_VIEW",
    "CONTENT_VIEW"
  ],
  SUPPORT: ["USER_VIEW", "WORKER_VIEW", "SUPPORT_TICKET_VIEW", "SUPPORT_TICKET_ASSIGN", "SUPPORT_TICKET_RESPOND"],
  ADMIN: ADMIN_PERMISSION_KEYS.filter((permissionKey) => permissionKey !== "FULL_ACCESS"),
  SUPER_ADMIN: ["FULL_ACCESS"]
};

type AdminPermissionKey = (typeof ADMIN_PERMISSION_KEYS)[number];

export { ADMIN_PERMISSION_KEYS, DANGEROUS_ADMIN_PERMISSIONS, DEFAULT_ROLE_PERMISSION_KEYS };
export type { AdminPermissionKey };
